### ISSUE TITLE
MSBuild can not be found

### ISSUE THREAD

**Issue by RononDex** [OmniSharp/omnisharp-roslyn#1610]
Since yesterday I keep getting this error when omnisharp starts up in vscode (omnisharp is set to latest version):
```
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        It looks like you have Mono 5.2.0 or greater installed but MSBuild could not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support.
```

This used to work without issues before. I noticed that msbuild version was increased in a recent commit. Maybe that causes omnisharp to no longer find my msbuild on linux?

**Comment by filipw** [comment]
can you post the full log?

**Comment by RononDex** [comment]
```
Starting OmniSharp server at 9/26/2019, 8:15:41 AM
    Target: /home/cobra/dev/AstroBotDev

OmniSharp server started with Mono 6.0.0.
    Path: /home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.4-beta.7/omnisharp/OmniSharp.exe
    PID: 43271

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        It looks like you have Mono 5.2.0 or greater installed but MSBuild could not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.0 - "/home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.4-beta.7/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.4-beta.7/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "/home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.4-beta.7/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
            MSBuildToolsPath = /home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.4-beta.7/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.4-beta.7/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /usr/lib/mono/xbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/cobra/dev/AstroBotDev'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/cobra/dev/AstroBotDev'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cobra/dev/AstroBotDev/AwesomeChatBot.Discord/AwesomeChatBot.DiscordWrapper.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cobra/dev/AstroBotDev/Astrobot/AstroBot/AstroBot.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cobra/dev/AstroBotDev/Astrobot/AstroBot.Test/AstroBot.Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cobra/dev/AstroBotDev/AwesomeChatBot/AwesomeChatBot/AwesomeChatBot.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/cobra/dev/AstroBotDev'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cobra/dev/AstroBotDev/AwesomeChatBot.Discord/AwesomeChatBot.DiscordWrapper.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/cobra/dev/AstroBotDev' on host 42229.
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cobra/dev/AstroBotDev/AwesomeChatBot.Discord/AwesomeChatBot.DiscordWrapper.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cobra/dev/AstroBotDev/AwesomeChatBot.Discord/AwesomeChatBot.DiscordWrapper.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cobra/dev/AstroBotDev/Astrobot/AstroBot/AstroBot.csproj
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cobra/dev/AstroBotDev/Astrobot/AstroBot/AstroBot.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cobra/dev/AstroBotDev/Astrobot/AstroBot/AstroBot.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cobra/dev/AstroBotDev/Astrobot/AstroBot.Test/AstroBot.Test.csproj
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cobra/dev/AstroBotDev/Astrobot/AstroBot.Test/AstroBot.Test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cobra/dev/AstroBotDev/Astrobot/AstroBot.Test/AstroBot.Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cobra/dev/AstroBotDev/AwesomeChatBot/AwesomeChatBot/AwesomeChatBot.csproj
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cobra/dev/AstroBotDev/AwesomeChatBot/AwesomeChatBot/AwesomeChatBot.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cobra/dev/AstroBotDev/AwesomeChatBot/AwesomeChatBot/AwesomeChatBot.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AwesomeChatBot.DiscordWrapper
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AstroBot
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AstroBot.Test
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AwesomeChatBot
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 86.

```

**Comment by RononDex** [comment]
dotnet --info output:
```
 cobra@ATLANTIS-SURFACE-ARCH  ~/dev/AstroBotDev                                                                08:16:51  Arc 
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.108/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.6 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
(dotnet sdk IS installed)

**Comment by Saancreed** [comment]
Since you are on Arch, it's no surprise that MSBuild cannot find your .NET Core SDK: not only it's installed in non-standard location, but also `/usr/bin/dotnet` is not a symlink and `DOTNET_ROOT` is not globally exported. Try the following (multiple at the same time if necessary):

* Replace `/usr/bin/dotnet` with a symlink to `/opt/dotnet/dotnet`
* Create a file in `/etc/profile.d`, e.g. `dotnet.sh`, with the following content: `export DOTNET_ROOT=/opt/dotnet` (you might need to adapt this for some login shells, and make sure you relog afterwards)
* Set `UseLegacySdkResolver` to `true` in your `omnisharp.json`

You *could* instead try exporting `MSBuildSdksPath`, but it's very prone to breakage and prevents you from using multiple SDK versions.

See [here](https://old.reddit.com/r/archlinux/comments/cx64r5/the_state_of_net_core_on_arch/) for some details on what I found about .NET Core packages in Arch.

**Comment by RononDex** [comment]
I can try that later when I am home, however a few comments of the bat:

- I am pretty sure /usr/bin/dotnet is already a symlink, since I don't have /opt/bin added to PATH and dotnet command works in console
 - I already have the following set in my bash profile: 
![image](https://user-images.githubusercontent.com/2249071/65752146-7593fa00-e10c-11e9-912a-5a57fa1dfcda.png)
 - It used to work just fine like that for over a year, and it suddenly changed two days ago. How does your comment explain that it worked before?

**Comment by Saancreed** [comment]
* I'm pretty sure that `/usr/bin/dotnet` is a shell script that execs `/opt/dotnet/dotnet`
* As for why it used to work, well, you said it yourself: a few days ago OmniSharp updated its MSBuild to 16.3, which might have changed SDK resolution logic. So, you could also try reverting to an older version of `omnisharp-roslyn` and if it works without any other changes, then bisect can get us more info.

You could also try getting `msbuild` and `msbuild-sdkresolver` from AUR, as your error log suggests that OmniSharp attempts to load extensions from legacy `xbuild` instead.

That said. what I *can* assure you is that it can work, but in my case it's probably because I build my own `mono`, `msbuild` and `omnisharp` packages from source: https://pastebin.com/PZiJ8bBQ (although it's not very relevant here).

**Comment by RononDex** [comment]
Just tried your suggestions, still does not work

**Comment by Saancreed** [comment]
Not even downgrading OmniSharp? If so, then I have no idea what else could be wrong with your setup, sorry.

**Comment by RononDex** [comment]
I havent tried downgrading omnisharp though

**Comment by filipw** [comment]
This should be fixed with the latest prerelease `"omnisharp.path": "1.34.4-beta.34"`

**Comment by RononDex** [comment]
I can confirm it is working with     Path: /home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.3/omnisharp/OmniSharp.exe

(After removing   ` "omnisharp.path": "latest",` from the settings in vscode)

**Comment by RononDex** [comment]
@filipw With the latest version I am still getting this a red omnisharp server icon in vscode:
![image](https://user-images.githubusercontent.com/2249071/65940523-ff073d00-e428-11e9-812c-40d20b413a35.png)

Log:
```
Starting OmniSharp server at 10/1/2019, 8:53:05 AM
    Target: /home/cobra/dev/RegiPegi

OmniSharp server started with Mono 6.0.0.
    Path: /home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.5-beta.6/omnisharp/OmniSharp.exe
    PID: 42792

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        It looks like you have Mono 5.2.0 or greater installed but MSBuild could not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.0 - "/home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.5-beta.6/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.5-beta.6/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "/home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.5-beta.6/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
            MSBuildToolsPath = /home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.5-beta.6/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/cobra/.vscode/extensions/ms-vscode.csharp-1.21.3/.omnisharp/1.34.5-beta.6/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /usr/lib/mono/xbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/cobra/dev/RegiPegi'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/cobra/dev/RegiPegi'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cobra/dev/RegiPegi/RegiPegi.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/cobra/dev/RegiPegi'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cobra/dev/RegiPegi/RegiPegi.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/cobra/dev/RegiPegi' on host 10583.
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cobra/dev/RegiPegi/RegiPegi.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cobra/dev/RegiPegi/RegiPegi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: RegiPegi
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 3.
```

**Comment by filipw** [comment]
can you upgrade mono to 6.4.0? looks like you have mono 6.0.0 but without msbuild.
even when omnisharp runs on embedded mono, it still uses global mono for the msbuild extension path and some other stuff

**Comment by RononDex** [comment]
It seems the Arch linux package of mono is out of date and fixed to 6.0.0

Will compile it myself when I get time (mono is quite huge project to compile)

**Comment by filipw** [comment]
you could also check `"omnisharp.useGlobalMono": "never"`

**Comment by ultimaweapon** [comment]
Install `msbuild-16-bin` from AUR and latest `mono` from official repository as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/3316#issuecomment-538807803) works for me.

**Comment by david-driscoll** [comment]
@RononDex can you confirm @ultimaweapon comment works for you as well?

**Comment by Rhiyo** [comment]
> Install `msbuild-16-bin` from AUR and latest `mono` from official repository as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/3316#issuecomment-538807803) works for me.

This worked for me as well.

**Comment by RononDex** [comment]
> 
> 
> @RononDex can you confirm @ultimaweapon comment works for you as well?

I will try that in a few hours

**Comment by RononDex** [comment]
I installed the packages and it still does not work.

MsBuild outputs version 16.3.0-ci
mono shows version 6.0

**Comment by ultimaweapon** [comment]
Try this before build:

```sh
export MSBuildSDKsPath=/opt/dotnet/sdk/$(dotnet --version)/Sdks
```

For me it required this variable otherwise it will error.

**Comment by RononDex** [comment]
@ultimaweapon I already have that one set:
![image](https://user-images.githubusercontent.com/2249071/67140439-9f979280-f25a-11e9-865f-b2854db40ca2.png)

**Comment by wirecat** [comment]
> Install `msbuild-16-bin` from AUR and latest `mono` from official repository as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/3316#issuecomment-538807803) works for me.

This also helped me.

**Comment by JasonKretzer** [comment]
> Install `msbuild-16-bin` from AUR and latest `mono` from official repository as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/3316#issuecomment-538807803) works for me.

I simply removed the msbuild-stable that I had initially installed and then installed msbuild-16-bin and debugging started working again.  Thanks, @ultimaweapon

**Comment by Krnlsoft** [comment]
> * /opt/dotnet/dotnet



> Since you are on Arch, it's no surprise that MSBuild cannot find your .NET Core SDK: not only it's installed in non-standard location, but also `/usr/bin/dotnet` is not a symlink and `DOTNET_ROOT` is not globally exported. Try the following (multiple at the same time if necessary):
> 
> * Replace `/usr/bin/dotnet` with a symlink to `/opt/dotnet/dotnet`
> * Create a file in `/etc/profile.d`, e.g. `dotnet.sh`, with the following content: `export DOTNET_ROOT=/opt/dotnet` (you might need to adapt this for some login shells, and make sure you relog afterwards)
> * Set `UseLegacySdkResolver` to `true` in your `omnisharp.json`
> 
> You _could_ instead try exporting `MSBuildSdksPath`, but it's very prone to breakage and prevents you from using multiple SDK versions.
> 
> See [here](https://old.reddit.com/r/archlinux/comments/cx64r5/the_state_of_net_core_on_arch/) for some details on what I found about .NET Core packages in Arch.

Worked for me without installing mono
Thanks!

**Comment by notaduck** [comment]
I can confirm that @Saancreed's solution also worked for me without installing `mono` and `msbuild-bin-16`.

**Comment by ultimaweapon** [comment]
@notaduck what steps you did? I was tried `DOTNET_ROOT` but no luck.

**Comment by notaduck** [comment]
> @notaduck what steps you did? I was tried `DOTNET_ROOT` but no luck.

I removed `/usr/bin/dotnet` and replaced it with `/opt/dotnet/dotnet`

```
sudo ln -s /opt/dotnet/dotnet /usr/bin/dotnet
```

Nothing else :)

**Comment by ultimaweapon** [comment]
Thanks for info. I just updated to the latest version and the previous working solution for me does not works anymore due to it refuse to use installed MSBuild because Mono is 6.0.0. Here is the log:

```
OmniSharp server started with Mono 6.0.0.
    Path: /home/ultimaweapon/.vscode/extensions/ms-vscode.csharp-1.21.6/.omnisharp/1.34.6/omnisharp/OmniSharp.exe
    PID: 18201

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        Found Mono MSBuild but it could not be used because it is version 6.0.0 and it needs to be >= 6.4.0. OmniSharp will use embedded Mono instead. If you encounter any problems with OmniSharp, it is recommended to upgrade your Mono to the latest version. See https://www.mono-project.com/download/stable/.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.3 - "/home/ultimaweapon/.vscode/extensions/ms-vscode.csharp-1.21.6/.omnisharp/1.34.6/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/ultimaweapon/.vscode/extensions/ms-vscode.csharp-1.21.6/.omnisharp/1.34.6/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.3 - "/home/ultimaweapon/.vscode/extensions/ms-vscode.csharp-1.21.6/.omnisharp/1.34.6/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
            MSBuildToolsPath = /home/ultimaweapon/.vscode/extensions/ms-vscode.csharp-1.21.6/.omnisharp/1.34.6/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/ultimaweapon/.vscode/extensions/ms-vscode.csharp-1.21.6/.omnisharp/1.34.6/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /usr/lib/mono/xbuild
```

No idea why it cannot find SDK:

```
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

**Comment by notaduck** [comment]
Do you have mono installed?

**Comment by ultimaweapon** [comment]
Yes. But unfortunately on Arch there is only 6.0.0 but the latest OmniSharp required 6.4.0. I just manually setup the previous version of OmniSharp now everything works again. I think I will stick with this version until Arch roll out Mono 6.4.0.

Thanks.

**Comment by notaduck** [comment]
Your welcome, however I'm on mono 6.0.0

**Comment by RodrigoLeiteF** [comment]
> Yes. But unfortunately on Arch there is only 6.0.0 but the latest OmniSharp required 6.4.0. I just manually setup the previous version of OmniSharp now everything works again. I think I will stick with this version until Arch roll out Mono 6.4.0.
> 
> Thanks.

You can install `mono-nightly` from the AUR to have Mono 6.7

**Comment by ultimaweapon** [comment]
Thanks but I don't like to use the nightly version.

**Comment by RononDex** [comment]
After installing `mono-nightly` it started working again

**Comment by masaeedu** [comment]
@Saancreed

> Since you are on Arch, it's no surprise that MSBuild cannot find your .NET Core SDK: not only it's installed in non-standard location, but also /usr/bin/dotnet is not a symlink

Does /usr/bin/dotnet being a symlink have some special significance from the perspective of msbuild resolving the dotnet sdk? E.g. does it try to follow symlinks and then decide adjacent to wherever the actual binary is located is where it'll find the SDKs?

**Comment by Saancreed** [comment]
@masaeedu I vaguely recall seeing some piece of code that attempts to find first `dotnet` in `$PATH` and resolve it with `realpath`, but now that I tried to locate it again, I actually couldn't. So I might have been mistaken here, or something was changed in 3.1 and it's just no longer there. Anyway, source is available [here](https://github.com/dotnet/core-setup/tree/release/3.1/src/corehost/cli/fxr), just in case you want to take a look.

**Comment by rodrigofbm** [comment]
I'm facing this issue. After installed `msbuild-bin-16` the War goes away but the autocomplete still dont work.

**Comment by davelsan** [comment]
I think this is fixed in 3.1.0.sdk100-2, but I'm not sure about 2.2.
Ref: [https://bugs.archlinux.org/task/60903](https://bugs.archlinux.org/task/60903)

I have tested it installing the latest 3.1.0 sdk, runtime and host packages:

```
community/dotnet-sdk 3.1.0.sdk100-2
community/dotnet-runtime 3.1.0.sdk100-2
community/dotnet-host 3.1.0.sdk100-2
```

With the following `fish` env config (adapt as needed for bash):

```fish
set -x PATH ~/.dotnet/tools $PATH
set -x DOTNET_ROOT (dirname (readlink (command -v dotnet)))
```

And the OmniSharp server is runnning without issues, including autocomplete.

**Comment by ultimaweapon** [comment]
With the latest version you don't need to do anything special anymore. It will work out of the box. You don't even need to install `msbuild-bin-16`.

**Comment by SuddenGunter** [comment]
>msbuild-16-bin
it was removed from AUR. Any idea why/what to use now?

**Comment by ultimaweapon** [comment]
You should not need to do anything special anymore. Just install the extension and it should work out of the box.
