### ISSUE TITLE
[LSP] Invalid returned CodeAction

### ISSUE THREAD

**Issue by CGNonofr** [OmniSharp/omnisharp-roslyn#2068]
Here an example of a serialized `CodeAction` response provided by omnisharp-roslyn:

```json
{
  "jsonrpc": "2.0",
  "id": 9,
  "result": [
    {
      "title": "Remove Unnecessary Usings",
      "kind": "refactor",
      "isPreferred": false,
      "diagnostics": [],
      "edit": {},
      "command": {
        "title": "Remove Unnecessary Usings",
        "command": "omnisharp/executeCodeAction",
        "arguments": [
          {
            "Uri": "file:///tmp/project/Main.cs",
            "Identifier": "Remove Unnecessary Usings",
            "Name": "Remove Unnecessary Usings",
            "Range": {
              "Start": {
                "Line": 6,
                "Character": 19
              },
              "End": {
                "Line": 6,
                "Character": 19
              }
            }
          }
        ]
      },
      "data": {
        "$$__handler_id__$$": "2d2f9bc2-5beb-4bb3-9b34-bd823e2cb425"
      }
    }
  ]
}
```

Refering to the [documentation](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction), `edit` should either be `undefined` or of type `WorkspaceEdit`

and `WorkspaceEdit` [should either provide `changes` or `documentChanges`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspaceEdit), but in the provided example, it's an empty object.

[vscode](https://github.com/microsoft/vscode-languageserver-node/blob/dae62de921d25964e8732411ca09e532dde992f5/types/src/main.ts#L1202) then doesn't consider it as a `CodeAction` and then think it's a legacy `Command` instead of a `CodeAction`, starting from here, nothing is working

It seems related to https://github.com/OmniSharp/omnisharp-roslyn/blob/ebabfb88bebd2989bc5348f9c022241314f064b1/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCodeActionHandler.cs#L102 but I don't know much C#

**Comment by razzmatazz** [comment]
HI @CGNonofr

The intent of 96600de was to workaround the issue where generating changesets for all the actions took too long on large projects. The design was such that we expect for the client to issue the `Command` specified so the server can push the changes via client when this command is executed (`omnisharp/executeCodeAction`). This workaround works on a couple of clients, `emacs-lsp` and `nvim`, IIRC. Is there something in vscode LSP client or wr.t. to this workaround that makes it unable to execute this `Command`.

The proper support for delayed code action resolution was added in [3.16#codeAction_resolve](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#codeAction_resolve). We are waiting for the #2044 PR to be merged before we can start using it in `omnisharp-roslyn`.

**Comment by CGNonofr** [comment]
Hi @razzmatazz

It seems that not providing the `edit` field at all (instead of an empty object) should be fine

**Comment by razzmatazz** [comment]
I might not know the context, but I see the code is checking (short-circuiting) on presence of the actual `edit` object too, in the line above, so providing it with a null or even undefined value would still not fix anything, right?
- https://github.com/microsoft/vscode-languageserver-node/blob/dae62de921d25964e8732411ca09e532dde992f5/types/src/main.ts#L1201

**Comment by CGNonofr** [comment]
This function is not called if `edit` is undefined:
- https://github.com/microsoft/vscode-languageserver-node/blob/dae62de921d25964e8732411ca09e532dde992f5/types/src/main.ts#L2956

**Comment by razzmatazz** [comment]
FYI @CGNonofr  -- I have added a PR that does away with `omnisharp/executeCodeAction` and uses the new "Standard" `codeAction/resolve` functionality which should fix this issue..

**Comment by CGNonofr** [comment]
Thanks 👍 I'll give it a try!

**Comment by CGNonofr** [comment]
I just tried the v1.37.15 and the issue still doesn't seem to be fixed
