### ISSUE TITLE
InvalidProjectFileException starting omnisharp

### ISSUE THREAD

**Issue by Alan01252** [OmniSharp/omnisharp-roslyn#2131]
**Issue**

Unable to load SDK's

The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' could not be found.

I have the following in omisharp.json

`{
  "MSBuild": {
    "UseLegacySdkResolver": true
  }
}
`
If that is set to false then I get

The SDK 'Microsoft.NET.Sdk' specified could not be found

dotnet --info

```

.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     nixos
 OS Version:  20.09.3436.6be212cce73
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /nix/store/55n5ihww23ali3plf4yqkncgcnvj9krf-dotnet-sdk-5.0.202/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [/nix/store/waj8a8z93a2r0x273bnkwj9jbfgj42a2-dotnet-core-combined/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/nix/store/waj8a8z93a2r0x273bnkwj9jbfgj42a2-dotnet-core-combined/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/nix/store/waj8a8z93a2r0x273bnkwj9jbfgj42a2-dotnet-core-combined/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Any help greatly appreciated :)

**Comment by Alan01252** [comment]
I fixed this by compiling the latest version of mono and running OmniSharp using that instead.

**Comment by Alan01252** [comment]
Mono JIT compiler version 6.12.0.137 (tarball Wed Apr  7 14:25:47 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by unspecd** [comment]
Thanks. I installed that version, but the error persists.
Well, I'll try to figure it out myself.

**Comment by Alan01252** [comment]
If it helps this is what I've got in my settings.json in vscode too

![image](https://user-images.githubusercontent.com/112859/117931885-a633a200-b2f7-11eb-9497-abe6036e9ff7.png)

**Comment by unspecd** [comment]
Looks like I found a workaround:
```console
$ export MSBuildEnableWorkloadResolver=false
```

**Comment by grinay** [comment]
Ok. Workaround works. Projects start loading. But still, error on running.
Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/libhostpolicy.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/libhostpolicy.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/libhostpolicy.dylib: mach-o, but wrong architecture
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6]

**Comment by mhutch** [comment]
I'm not familiar with how OmniSharp locates MSBuild, but updating MSBuild (via updating Mono) is the correct solution to this. The new MSBuild SDK resolvers in the .NET 5 SDK override a new virtual method in the SDK resolver base class, and hence cannot be loaded by older versions of MSBuild that do not have that method.

The workaround of disabling the workload resolver via `MSBuildEnableWorkloadResolver=false` shouldn't cause any problems as AFAIK there are currently no "workloads" (optional SDK components) on Linux. However, I would suggest removing the workaround once you have a newer MSBuild so as not to break workloads once they are available/present.

**Comment by filipw** [comment]
Thanks a lot for this comment, I agree. 

The bundled MSBuild of OmniSharp can also handle this correctly now, so setting `"omnisharp.useGlobalMono":"never"` or adding an `omnisharp.json` file to the root of your project with the content

```
{
   "msbuild": {
       "useBundledOnly": true
   }
}
```

should also work. There may however be valid reasons to use global Mono (e.g. OmniSharp doesn't ship with reference assemblies for desktop .NET).

**Comment by mhutch** [comment]
I'm not sure exactly what's going on here TBH, as MSBuild normally only loads SDK resolvers from its own install directory. My guess is OmniSharp is somehow making it load the newer resolvers from the SDK, but that's just a guess.
